//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.29 at 11:51:34 ÏÂÎç CST 
//


package org.hi.metadata.hsc.context.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}childServiceName"/>
 *         &lt;element ref="{}childEntityName"/>
 *         &lt;element ref="{}childForeignKey"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "childServiceName",
    "childEntityName",
    "childForeignKey"
})
@XmlRootElement(name = "childEntity")
public class ChildEntity {

    @XmlElement(required = true)
    protected String childServiceName;
    @XmlElement(required = true)
    protected String childEntityName;
    @XmlElement(required = true)
    protected String childForeignKey;

    /**
     * Gets the value of the childServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildServiceName() {
        return childServiceName;
    }

    /**
     * Sets the value of the childServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildServiceName(String value) {
        this.childServiceName = value;
    }

    /**
     * Gets the value of the childEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildEntityName() {
        return childEntityName;
    }

    /**
     * Sets the value of the childEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildEntityName(String value) {
        this.childEntityName = value;
    }

    /**
     * Gets the value of the childForeignKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildForeignKey() {
        return childForeignKey;
    }

    /**
     * Sets the value of the childForeignKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildForeignKey(String value) {
        this.childForeignKey = value;
    }

}
