//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.29 at 11:51:34 ÏÂÎç CST 
//


package org.hi.metadata.hsc.context.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}enuValue"/>
 *         &lt;element ref="{}enuLabel"/>
 *         &lt;element ref="{}enuCode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enuValue",
    "enuLabel",
    "enuCode"
})
@XmlRootElement(name = "enumeration")
public class Enumeration {

    @XmlElement(required = true)
    protected String enuValue;
    @XmlElement(required = true)
    protected String enuLabel;
    @XmlElement(required = true)
    protected String enuCode;

    /**
     * Gets the value of the enuValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnuValue() {
        return enuValue;
    }

    /**
     * Sets the value of the enuValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnuValue(String value) {
        this.enuValue = value;
    }

    /**
     * Gets the value of the enuLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnuLabel() {
        return enuLabel;
    }

    /**
     * Sets the value of the enuLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnuLabel(String value) {
        this.enuLabel = value;
    }

    /**
     * Gets the value of the enuCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnuCode() {
        return enuCode;
    }

    /**
     * Sets the value of the enuCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnuCode(String value) {
        this.enuCode = value;
    }

}
