//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.29 at 11:51:34 ÏÂÎç CST 
//


package org.hi.metadata.hsc.context.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}fieldName"/>
 *         &lt;element ref="{}fieldLabel"/>
 *         &lt;element ref="{}isPrimaryKey"/>
 *         &lt;element ref="{}isReadOnly"/>
 *         &lt;element ref="{}isSearch"/>
 *         &lt;element ref="{}isListDisplay"/>
 *         &lt;element ref="{}isHidden"/>
 *         &lt;element ref="{}isFull"/>
 *         &lt;element ref="{}isMainLookup"/>
 *         &lt;element ref="{}isParent"/>
 *         &lt;element ref="{}fieldType"/>
 *         &lt;element ref="{}length"/>
 *         &lt;element ref="{}scale"/>
 *         &lt;element ref="{}defaultValue"/>
 *         &lt;element ref="{}validator"/>
 *         &lt;element ref="{}enumerationEntity"/>
 *         &lt;element ref="{}lookupEntity"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fieldName",
    "fieldLabel",
    "isPrimaryKey",
    "isReadOnly",
    "isSearch",
    "isListDisplay",
    "isHidden",
    "isFull",
    "isMainLookup",
    "isParent",
    "fieldType",
    "length",
    "scale",
    "defaultValue",
    "validator",
    "enumerationEntity",
    "lookupEntity"
})
@XmlRootElement(name = "field")
public class Field {

    @XmlElement(required = true)
    protected String fieldName;
    @XmlElement(required = true)
    protected String fieldLabel;
    @XmlElement(defaultValue = "false")
    protected boolean isPrimaryKey;
    @XmlElement(defaultValue = "false")
    protected boolean isReadOnly;
    @XmlElement(defaultValue = "false")
    protected boolean isSearch;
    @XmlElement(defaultValue = "true")
    protected boolean isListDisplay;
    @XmlElement(defaultValue = "false")
    protected boolean isHidden;
    @XmlElement(defaultValue = "false")
    protected boolean isFull;
    @XmlElement(defaultValue = "false")
    protected boolean isMainLookup;
    @XmlElement(defaultValue = "false")
    protected boolean isParent;
    protected int fieldType;
    protected int length;
    protected int scale;
    @XmlElement(required = true)
    protected String defaultValue;
    @XmlElement(required = true)
    protected String validator;
    @XmlElement(required = true)
    protected String enumerationEntity;
    @XmlElement(required = true)
    protected LookupEntity lookupEntity;

    /**
     * Gets the value of the fieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Sets the value of the fieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldName(String value) {
        this.fieldName = value;
    }

    /**
     * Gets the value of the fieldLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldLabel() {
        return fieldLabel;
    }

    /**
     * Sets the value of the fieldLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldLabel(String value) {
        this.fieldLabel = value;
    }

    /**
     * Gets the value of the isPrimaryKey property.
     * 
     */
    public boolean isIsPrimaryKey() {
        return isPrimaryKey;
    }

    /**
     * Sets the value of the isPrimaryKey property.
     * 
     */
    public void setIsPrimaryKey(boolean value) {
        this.isPrimaryKey = value;
    }

    /**
     * Gets the value of the isReadOnly property.
     * 
     */
    public boolean isIsReadOnly() {
        return isReadOnly;
    }

    /**
     * Sets the value of the isReadOnly property.
     * 
     */
    public void setIsReadOnly(boolean value) {
        this.isReadOnly = value;
    }

    /**
     * Gets the value of the isSearch property.
     * 
     */
    public boolean isIsSearch() {
        return isSearch;
    }

    /**
     * Sets the value of the isSearch property.
     * 
     */
    public void setIsSearch(boolean value) {
        this.isSearch = value;
    }

    /**
     * Gets the value of the isListDisplay property.
     * 
     */
    public boolean isIsListDisplay() {
        return isListDisplay;
    }

    /**
     * Sets the value of the isListDisplay property.
     * 
     */
    public void setIsListDisplay(boolean value) {
        this.isListDisplay = value;
    }

    /**
     * Gets the value of the isHidden property.
     * 
     */
    public boolean isIsHidden() {
        return isHidden;
    }

    /**
     * Sets the value of the isHidden property.
     * 
     */
    public void setIsHidden(boolean value) {
        this.isHidden = value;
    }

    /**
     * Gets the value of the isFull property.
     * 
     */
    public boolean isIsFull() {
        return isFull;
    }

    /**
     * Sets the value of the isFull property.
     * 
     */
    public void setIsFull(boolean value) {
        this.isFull = value;
    }

    /**
     * Gets the value of the isMainLookup property.
     * 
     */
    public boolean isIsMainLookup() {
        return isMainLookup;
    }

    /**
     * Sets the value of the isMainLookup property.
     * 
     */
    public void setIsMainLookup(boolean value) {
        this.isMainLookup = value;
    }

    /**
     * Gets the value of the isParent property.
     * 
     */
    public boolean isIsParent() {
        return isParent;
    }

    /**
     * Sets the value of the isParent property.
     * 
     */
    public void setIsParent(boolean value) {
        this.isParent = value;
    }

    /**
     * Gets the value of the fieldType property.
     * 
     */
    public int getFieldType() {
        return fieldType;
    }

    /**
     * Sets the value of the fieldType property.
     * 
     */
    public void setFieldType(int value) {
        this.fieldType = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public int getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(int value) {
        this.length = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     */
    public int getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     */
    public void setScale(int value) {
        this.scale = value;
    }

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the validator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidator() {
        return validator;
    }

    /**
     * Sets the value of the validator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidator(String value) {
        this.validator = value;
    }

    /**
     * Gets the value of the enumerationEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnumerationEntity() {
        return enumerationEntity;
    }

    /**
     * Sets the value of the enumerationEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnumerationEntity(String value) {
        this.enumerationEntity = value;
    }

    /**
     * Gets the value of the lookupEntity property.
     * 
     * @return
     *     possible object is
     *     {@link LookupEntity }
     *     
     */
    public LookupEntity getLookupEntity() {
        return lookupEntity;
    }

    /**
     * Sets the value of the lookupEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookupEntity }
     *     
     */
    public void setLookupEntity(LookupEntity value) {
        this.lookupEntity = value;
    }

}
