//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.10 at 11:48:24 ÉÏÎç CST 
//


package org.hi.metadata.hsc.context.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}parentServiceName"/>
 *         &lt;element ref="{}parentEntityName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parentServiceName",
    "parentEntityName"
})
@XmlRootElement(name = "parentEntity")
public class ParentEntity {

    @XmlElement(required = true)
    protected String parentServiceName;
    @XmlElement(required = true)
    protected String parentEntityName;

    /**
     * Gets the value of the parentServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentServiceName() {
        return parentServiceName;
    }

    /**
     * Sets the value of the parentServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentServiceName(String value) {
        this.parentServiceName = value;
    }

    /**
     * Gets the value of the parentEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentEntityName() {
        return parentEntityName;
    }

    /**
     * Sets the value of the parentEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentEntityName(String value) {
        this.parentEntityName = value;
    }

}
