//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.07 at 07:44:18 ÏÂÎç CST 
//


package org.hi.metadata.hsc.context.environment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}homePath"/>
 *         &lt;element ref="{}libraryDir"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "homePath",
    "libraryDir"
})
@XmlRootElement(name = "javaEnvironment")
public class JavaEnvironment {

    @XmlElement(required = true)
    protected String homePath;
    @XmlElement(required = true)
    protected String libraryDir;

    /**
     * Gets the value of the homePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomePath() {
        return homePath;
    }

    /**
     * Sets the value of the homePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomePath(String value) {
        this.homePath = value;
    }

    /**
     * Gets the value of the libraryDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibraryDir() {
        return libraryDir;
    }

    /**
     * Sets the value of the libraryDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibraryDir(String value) {
        this.libraryDir = value;
    }

}
