//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.29 at 11:51:34 ÏÂÎç CST 
//


package org.hi.metadata.hsc.context.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}extendServiceName"/>
 *         &lt;element ref="{}extendEntityName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extendServiceName",
    "extendEntityName"
})
@XmlRootElement(name = "extendEntity")
public class ExtendEntity {

    @XmlElement(required = true)
    protected String extendServiceName;
    @XmlElement(required = true)
    protected String extendEntityName;

    /**
     * Gets the value of the extendServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendServiceName() {
        return extendServiceName;
    }

    /**
     * Sets the value of the extendServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendServiceName(String value) {
        this.extendServiceName = value;
    }

    /**
     * Gets the value of the extendEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendEntityName() {
        return extendEntityName;
    }

    /**
     * Sets the value of the extendEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendEntityName(String value) {
        this.extendEntityName = value;
    }

}
