//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.29 at 11:51:34 ÏÂÎç CST 
//


package org.hi.metadata.hsc.context.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}lkServiceName"/>
 *         &lt;element ref="{}lkEntityName"/>
 *         &lt;element ref="{}isLkForeignKey"/>
 *         &lt;element ref="{}mainLkFieldName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lkServiceName",
    "lkEntityName",
    "isLkForeignKey",
    "mainLkFieldName"
})
@XmlRootElement(name = "lookupEntity")
public class LookupEntity {

    @XmlElement(required = true)
    protected String lkServiceName;
    @XmlElement(required = true)
    protected String lkEntityName;
    @XmlElement(defaultValue = "false")
    protected boolean isLkForeignKey;
    @XmlElement(required = true)
    protected String mainLkFieldName;

    /**
     * Gets the value of the lkServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLkServiceName() {
        return lkServiceName;
    }

    /**
     * Sets the value of the lkServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLkServiceName(String value) {
        this.lkServiceName = value;
    }

    /**
     * Gets the value of the lkEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLkEntityName() {
        return lkEntityName;
    }

    /**
     * Sets the value of the lkEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLkEntityName(String value) {
        this.lkEntityName = value;
    }

    /**
     * Gets the value of the isLkForeignKey property.
     * 
     */
    public boolean isIsLkForeignKey() {
        return isLkForeignKey;
    }

    /**
     * Sets the value of the isLkForeignKey property.
     * 
     */
    public void setIsLkForeignKey(boolean value) {
        this.isLkForeignKey = value;
    }

    /**
     * Gets the value of the mainLkFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainLkFieldName() {
        return mainLkFieldName;
    }

    /**
     * Sets the value of the mainLkFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainLkFieldName(String value) {
        this.mainLkFieldName = value;
    }

}
